[package]
name = "noraft"
version = "0.6.2"
edition = "2024"
license = "MIT"
description = "Minimal, feature-complete no_std Raft for Rust - no I/O, no dependencies"
homepage = "https://github.com/sile/noraft"
repository = "https://github.com/sile/noraft"
readme = "README.md"
categories = ["algorithms", "no-std"]

[dependencies]

[dev-dependencies]
noprop = "0.1.0"
rand = "0.10.0"
